add_rules("mode.debug", "mode.release")
add_requires("spdlog")
add_requires("cpr")
add_requires("boost", {configs = {asio = true,json = true}})
add_requires("jsoncpp")
add_requires("yaml-cpp")
target("engine")
    set_kind("binary")
    set_languages("c++23")
    add_files("src/*.cpp")
    set_rundir("..")
    add_files("../data/logs/enginelog_c++/commonlog.cpp")
    add_files("../configs/config_manager.cpp")
    add_files("files/global.cpp")
    add_files("files/bridge.cpp")
    add_packages("spdlog","cpr","boost","jsoncpp","yaml-cpp")
target("Kubernetics")
    set_kind("binary")
    set_languages("c++23")
    add_files("kubernetics/*.cpp")
    set_rundir("..")
    add_files("../data/logs/enginelog_c++/commonlog.cpp")
    add_files("../configs/config_manager.cpp")
    add_files("files/global.cpp")
    add_files("files/bridge.cpp")
    add_packages("spdlog","cpr","boost","jsoncpp","yaml-cpp")
