remote_executor:
    ipv4: "10.199.99.241"
    port: 22
    username: "rohan-sivadas"
    key_filename: "/home/abhinandps/.ssh/testing"
remote_executor1:
    username: "abhinandps"
    host: "localhost"
docker_client:
    docker_port_path: "/var/run/docker.sock"
    host: "localhost"
kubernetics:
    value: "~/.kube/config"
    host: "localhost"
    certificate: "/home/abhinandps/.minikube/profiles/minikube/client.crt"
    private_key: "/home/abhinandps/.minikube/profiles/minikube/client.key"
CloudGpu:
    host: "ssh.lightning.ai"
    private_key: "/home/abhinandps/.ssh/lightning_rsa"
    Username: "s_01m1bv61ybb7c99gq7j28gppdk"
